#ifndef STATUSES_HPP
# define STATUSES_HPP

# define READY_FOR_REQUEST 1
# define CHUNKED_RECEIVE 2
# define BODYBUFF_RECEIVE 3
# define READY_TO_RESPONSE 4
# define CURRENTLY_RESPONDING 5
# define LENGTH_RECEIVING 10
# define BUF_RECEIVING 11

#endif